### ISSUE TITLE
clang-format job shows code path to correct that are not modified by PR

### ISSUE THREAD

**Issue by Sheetalpamecha** [gluster/build-jobs#112]
clang-format passes successfully but still shows a warning message on some
of the Pull Requests and suggest edits in the code that is not been
changed by respective PR.

https://github.com/gluster/build-jobs/blob/main/build-gluster-org/scripts/clang-format.py 
Script doesn't fail for appropriate patches instead show a comment for all patches

**Comment by Sheetalpamecha** [comment]
@rakshithakamath94

**Comment by Sheetalpamecha** [comment]
Can you tell me which clang-format version does jenkins machine have?

**Comment by mscherer** [comment]
That's Fedora 32 nodes, so clang-10.0.1-3.fc32.x86_64 

We should upgrade them to F34.
